#!/usr/bin/env python3
"""Build the Kaggle submission artifacts for ContinualHarness.

Produces two files under kaggle/dist/ (gitignored):

1. ``ch-kaggle-source-bundle.zip`` — the minimal ContinualHarness source tree
   (plus fallback ``openai`` wheels and a marker/metadata file). Upload this
   zip as a Kaggle *dataset*; Kaggle extracts it so the notebook can locate it
   by its ``ch-kaggle-bundle.json`` marker.
2. ``continual-harness-kaggle.ipynb`` — the submission notebook. Upload it as
   a Kaggle *notebook* for the ``arc-prize-2026-arc-agi-3`` competition and
   attach: the bundle dataset, ``driessmit1/arc3-vllm-h100-wheelhouse-v3``,
   and ``driessmit1/vrfai-qwen3-6-27b-fp8-hf-snapshot``. Select the
   RTX Pro 6000 accelerator.

The bundle intentionally excludes the non-ContinualHarness agent templates
(langgraph/smolagents/llm) and every ``.env*`` file: on Kaggle all
configuration comes from the notebook's environment variables, and the extra
templates would drag in dependencies that are absent from the offline
competition wheelhouse. A pruned ``agents/__init__.py`` (embedded below)
replaces the repo one inside the zip.

Usage:
    uv run python make_kaggle_bundle.py [--skip-wheels] [--dist-dir PATH]
"""

from __future__ import annotations

import argparse
import ast
import hashlib
import json
import subprocess
import sys
import zipfile
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent
DEFAULT_DIST_DIR = REPO_ROOT / "kaggle" / "dist"
BUNDLE_ZIP_NAME = "ch-kaggle-source-bundle.zip"
NOTEBOOK_NAME = "continual-harness-kaggle.ipynb"
MARKER_NAME = "ch-kaggle-bundle.json"
SRC_PREFIX = "src/ARC-AGI-3-Agents"

# Only the `openai` client is missing from the competition wheelhouse (which
# already provides python-dotenv/pillow/pydantic/numpy/requests as arc-agi
# dependencies). cp312 matches the Kaggle image (all competition wheels are
# cp312).
WHEEL_PACKAGES = ("openai",)
WHEEL_PYTHON_VERSION = "3.12"
WHEEL_PLATFORMS = (
    "manylinux2014_x86_64",
    "manylinux_2_17_x86_64",
    "manylinux_2_28_x86_64",
)

# Explicit source manifest: the minimal closure for `main.py
# --agent=continualharness` (plus the dependency-free Random agent for smoke
# tests). The AST check below fails the build if this list ever goes stale.
SOURCE_FILES = (
    "main.py",
    "agents/agent.py",
    "agents/swarm.py",
    "agents/recorder.py",
    "agents/run_artifacts.py",
    "agents/tracing.py",
    "agents/templates/random_agent.py",
    "agents/templates/continual_harness_agent.py",
    "agents/templates/utils/vlm_backend.py",
)
SOURCE_GLOBS = (
    ("agents/templates/continual_harness", "*.py"),
    ("agents/templates/continual_harness/prompts", "*.py"),
    ("agents/templates/continual_harness/prompts", "*.md"),
)

# Replaces agents/__init__.py inside the bundle: registers only the agents the
# Kaggle run needs, so importing `agents` does not pull langchain/langgraph/
# smolagents/google-genai (none of which exist in the offline wheelhouse).
PRUNED_AGENTS_INIT = '''\
"""Kaggle-minimal agent registry (generated by make_kaggle_bundle.py).

Only ContinualHarness and Random are registered; the other upstream templates
need packages that are not available in the offline Kaggle environment.
"""

from typing import Type, cast

from dotenv import load_dotenv

from .agent import Agent, Playback
from .recorder import Recorder
from .swarm import Swarm
from .templates.continual_harness_agent import ContinualHarness
from .templates.random_agent import Random

load_dotenv()

AVAILABLE_AGENTS: dict[str, Type[Agent]] = {
    cls.__name__.lower(): cast(Type[Agent], cls)
    for cls in Agent.__subclasses__()
    if cls.__name__ != "Playback"
}

# add all the recording files as valid agent names
for rec in Recorder.list():
    AVAILABLE_AGENTS[rec] = Playback

__all__ = [
    "Agent",
    "AVAILABLE_AGENTS",
    "ContinualHarness",
    "Playback",
    "Random",
    "Recorder",
    "Swarm",
]
'''


def collect_sources() -> dict[str, Path]:
    """Map bundle-relative path -> absolute repo path for every source file."""
    sources: dict[str, Path] = {}
    missing: list[str] = []
    for rel in SOURCE_FILES:
        path = REPO_ROOT / rel
        if path.is_file():
            sources[rel] = path
        else:
            missing.append(rel)
    for rel_dir, pattern in SOURCE_GLOBS:
        base = REPO_ROOT / rel_dir
        if not base.is_dir():
            missing.append(f"{rel_dir}/ ({pattern})")
            continue
        for path in sorted(base.glob(pattern)):
            if "__pycache__" in path.parts:
                continue
            sources[path.relative_to(REPO_ROOT).as_posix()] = path
    if missing:
        raise FileNotFoundError(f"Source manifest entries not found: {missing}")
    return sources


def _module_name(rel: str) -> str:
    parts = rel[: -len(".py")].split("/")
    if parts[-1] == "__init__":
        parts = parts[:-1]
    return ".".join(parts)


def _available_modules(py_rels: list[str]) -> set[str]:
    """Bundled module names plus every parent (namespace) package."""
    available: set[str] = set()
    for rel in py_rels:
        parts = _module_name(rel).split(".")
        for i in range(1, len(parts) + 1):
            available.add(".".join(parts[:i]))
    return available


def check_imports(sources: dict[str, Path]) -> None:
    """Fail if any relative / `agents.*` import escapes the bundle.

    Third-party imports are not policed (some, like the Gemini SDK, are
    intentionally lazy and never reached on Kaggle).
    """
    py_files: dict[str, str] = {
        rel: path.read_text(encoding="utf-8")
        for rel, path in sources.items()
        if rel.endswith(".py")
    }
    py_files["agents/__init__.py"] = PRUNED_AGENTS_INIT
    available = _available_modules(list(py_files))
    problems: list[str] = []

    for rel, text in py_files.items():
        module = _module_name(rel)
        is_package = rel.endswith("__init__.py")
        package_parts = module.split(".") if is_package else module.split(".")[:-1]
        tree = ast.parse(text, filename=rel)
        for node in ast.walk(tree):
            targets: list[str] = []
            if isinstance(node, ast.ImportFrom):
                if node.level > 0:
                    base = package_parts[: len(package_parts) - (node.level - 1)]
                    prefix = base + (node.module.split(".") if node.module else [])
                elif node.module and node.module.split(".")[0] == "agents":
                    prefix = node.module.split(".")
                else:
                    continue
                target = ".".join(prefix)
                # `from pkg import name` is fine when pkg is bundled, or when
                # every imported name is itself a bundled submodule.
                if target not in available and not all(
                    f"{target}.{alias.name}" in available for alias in node.names
                ):
                    targets.append(target)
            elif isinstance(node, ast.Import):
                targets.extend(
                    alias.name
                    for alias in node.names
                    if alias.name.split(".")[0] == "agents"
                    and alias.name not in available
                )
            problems.extend(f"{rel}: unresolved import {t!r}" for t in targets)

    if problems:
        raise RuntimeError(
            "Bundle import check failed — extend SOURCE_FILES/SOURCE_GLOBS:\n"
            + "\n".join(problems)
        )


def _pip_command() -> list[str]:
    """First working pip invocation (uv venvs usually ship without pip)."""
    candidates = (
        [sys.executable, "-m", "pip"],
        ["uv", "run", "--with", "pip", "python", "-m", "pip"],
        ["pip3"],
    )
    for cmd in candidates:
        try:
            result = subprocess.run([*cmd, "--version"], capture_output=True, text=True)
        except OSError:
            continue
        if result.returncode == 0:
            return list(cmd)
    raise RuntimeError(
        "No usable pip found (tried python -m pip, uv run --with pip, pip3). "
        "Install pip or rerun with --skip-wheels."
    )


def download_wheels(wheels_dir: Path) -> None:
    wheels_dir.mkdir(parents=True, exist_ok=True)
    cmd = [
        *_pip_command(),
        "download",
        *WHEEL_PACKAGES,
        "--dest",
        str(wheels_dir),
        "--only-binary",
        ":all:",
        "--python-version",
        WHEEL_PYTHON_VERSION,
    ]
    for platform in WHEEL_PLATFORMS:
        cmd.extend(["--platform", platform])
    print(f"Downloading fallback wheels: {' '.join(WHEEL_PACKAGES)}")
    subprocess.run(cmd, check=True)


def _git_info() -> tuple[str, bool]:
    try:
        commit = subprocess.run(
            ["git", "rev-parse", "HEAD"],
            cwd=REPO_ROOT,
            capture_output=True,
            text=True,
            check=True,
        ).stdout.strip()
        status = subprocess.run(
            ["git", "status", "--porcelain"],
            cwd=REPO_ROOT,
            capture_output=True,
            text=True,
            check=True,
        ).stdout.strip()
        return commit, bool(status)
    except (OSError, subprocess.CalledProcessError):
        return "unknown", False


def build_marker(sources: dict[str, Path], wheel_names: list[str]) -> str:
    commit, dirty = _git_info()
    files = {
        rel: hashlib.sha256(path.read_bytes()).hexdigest()
        for rel, path in sorted(sources.items())
    }
    files["agents/__init__.py"] = hashlib.sha256(
        PRUNED_AGENTS_INIT.encode("utf-8")
    ).hexdigest()
    marker = {
        "bundle": "continual-harness-kaggle",
        "created_utc": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "git_commit": commit,
        "git_dirty": dirty,
        "source_prefix": SRC_PREFIX,
        "files": files,
        "wheels": sorted(wheel_names),
        "generator": "make_kaggle_bundle.py",
    }
    return json.dumps(marker, indent=2, sort_keys=True) + "\n"


README_DATASET = """\
# ContinualHarness Kaggle source bundle

Minimal source snapshot of the ContinualHarness agent (a fork of ARC Prize's
ARC-AGI-3-Agents) for the `arc-prize-2026-arc-agi-3` competition, plus
fallback `openai` client wheels for the offline rerun. The companion Kaggle
notebook locates this dataset by the `ch-kaggle-bundle.json` marker, copies
`src/ARC-AGI-3-Agents/` into `/kaggle/working`, and owns all run logic.

Regenerate with `uv run python make_kaggle_bundle.py` at the fork root.
No credentials or API keys are included.
"""


def write_zip(zip_path: Path, sources: dict[str, Path], wheels_dir: Path) -> None:
    zip_path.parent.mkdir(parents=True, exist_ok=True)
    wheel_files = sorted(wheels_dir.glob("*.whl")) if wheels_dir.is_dir() else []
    marker = build_marker(sources, [w.name for w in wheel_files])
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr(MARKER_NAME, marker)
        zf.writestr("README.dataset.md", README_DATASET)
        for wheel in wheel_files:
            zf.write(wheel, f"wheels/{wheel.name}")
        zf.writestr(f"{SRC_PREFIX}/agents/__init__.py", PRUNED_AGENTS_INIT)
        for rel, path in sorted(sources.items()):
            zf.write(path, f"{SRC_PREFIX}/{rel}")
    print(f"Wrote {zip_path} ({zip_path.stat().st_size / 1024:.0f} KiB)")


# --------------------------------------------------------------------------
# Notebook
# --------------------------------------------------------------------------
# Cells are kept as plain strings: the notebook code runs only on Kaggle and
# must not be type-checked/imported here. Layout mirrors the proven TAAF
# milestone notebook (kaggle/example/).

_CELL_INTRO_MD = """\
# ContinualHarness — ARC-AGI-3 submission

Runs the **ContinualHarness** agent (a self-evolving VLM harness: prompt,
skills, subagents, and memory evolve during play) against ARC-AGI-3, powered
by **Qwen3.6-27B-FP8** served locally with vLLM.

**Required inputs** (Add Input, in addition to the competition data):
1. the ContinualHarness source bundle dataset (contains `ch-kaggle-bundle.json`),
2. `driessmit1/arc3-vllm-h100-wheelhouse-v3` — offline vLLM wheelhouse,
3. `driessmit1/vrfai-qwen3-6-27b-fp8-hf-snapshot` — model weights.

**Accelerator**: select **RTX Pro 6000** manually if you copy this notebook.

Behavior:
- **Interactive "Save & Run All"**: plays the competition's bundled offline
  games, time-boxed by `TEST_BUDGET_S`, then writes a placeholder
  `submission.parquet` (required for the version to be submittable).
- **Competition rerun** (`KAGGLE_IS_COMPETITION_RERUN`): waits for the
  evaluation gateway and plays the live Arcade, capped at
  `MAX_CONCURRENT_GAMES` concurrent games.

Only infrastructure lives in this notebook; the agent code comes from the
bundle dataset.
"""

_CELL_SETUP = """\
import json
import os
import shutil
import signal
import subprocess
import sys
import threading
import time
import urllib.error
import urllib.request
from pathlib import Path

# True only inside a real competition rerun; switches game source + budget.
TRUE_SUBMISSION = os.environ.get("KAGGLE_IS_COMPETITION_RERUN", "").strip().lower() in {"1", "true"}
NOTEBOOK_START = time.monotonic()

# --- Editable knobs ---------------------------------------------------------
MAX_CONCURRENT_GAMES = 30       # cap on games playing simultaneously
MODEL_KEY = "qwen3.6-27b"       # key in the harness's vLLM model registry
MAX_MODEL_LEN = 262144           # served context; must match VLLM_MAX_MODEL_LEN below
GPU_MEMORY_UTILIZATION = 0.98
VLLM_PORT = 8000
ENABLE_MTP = False              # qwen3_next_mtp speculative decoding (off = proven config)
# Server-side default sampling for ALL inference requests: the harness's vLLM
# backend sends no sampling params, so these (not vLLM's neutral defaults)
# govern play. Per-request values (e.g. the temperature=0 smoke tests) still win.
SAMPLING = {
    "temperature": 0.6,
    "top_p": 0.95,
    "top_k": 20,
    "min_p": 0.0,
    "presence_penalty": 0.0,
    "repetition_penalty": 1.0,
}
TEST_BUDGET_S = 3 * 3600        # interactive run: soft deadline, measured from notebook start
RERUN_BUDGET_S = int(9.5 * 3600)  # rerun: leave ~30 min of the 9 h session for teardown

COMPETITION_DIR = Path("/kaggle/input/competitions/arc-prize-2026-arc-agi-3")
ARC_WHEELS_DIR = COMPETITION_DIR / "arc_agi_3_wheels"
ENV_FILES_DIR = COMPETITION_DIR / "environment_files"
WORKING_DIR = Path("/kaggle/working")
REPO_DIR = WORKING_DIR / "ARC-AGI-3-Agents"
VLLM_SITE_PACKAGES = WORKING_DIR / "vllm-site-packages"
VLLM_LOG = WORKING_DIR / "vllm-server.log"

os.environ["MPLBACKEND"] = "Agg"
# Pin arc_agi's cached level_reset_only before any client is built (RESET keeps the level).
os.environ["ONLY_RESET_LEVELS"] = "true"
# The CUDA toolkit is off the linker path on Kaggle GPU images.
cuda_lib = "/usr/local/nvidia/lib64"
os.environ["LIBRARY_PATH"] = os.pathsep.join(
    p for p in [cuda_lib, *os.environ.get("LIBRARY_PATH", "").split(os.pathsep)] if p
)

WORKING_DIR.mkdir(parents=True, exist_ok=True)
print("TRUE_SUBMISSION =", TRUE_SUBMISSION)
print(sys.version)
subprocess.run(["nvidia-smi", "--query-gpu=name,memory.total", "--format=csv"], check=False)
"""

_CELL_ARC_MD = """\
## 1. Install the ARC runtime (offline)

`arc-agi` + `arcengine` come from the competition wheelhouse; the submission
environment has no internet.
"""

_CELL_ARC = """\
subprocess.check_call(
    [
        sys.executable, "-m", "pip", "install",
        "--quiet", "--no-index", "--no-warn-conflicts", "--disable-pip-version-check",
        "--find-links", str(ARC_WHEELS_DIR),
        "arc-agi",
    ],
    stdout=subprocess.DEVNULL,
)
import importlib.metadata

print("arc-agi", importlib.metadata.version("arc-agi"),
      "| arcengine", importlib.metadata.version("arcengine"))
"""

_CELL_BUNDLE_MD = """\
## 2. Load the ContinualHarness source bundle

Locate the bundle dataset by its marker file, copy the source tree into the
writable working directory (run logs land inside it), and make sure the
`openai` client is importable (fallback wheels ship in the bundle).
"""

_CELL_BUNDLE = """\
BUNDLE_MARKER = "ch-kaggle-bundle.json"
markers = sorted(Path("/kaggle/input").rglob(BUNDLE_MARKER))
if not markers:
    raise RuntimeError("ContinualHarness source bundle not found under /kaggle/input")
BUNDLE_DIR = markers[0].parent
info = json.loads((BUNDLE_DIR / BUNDLE_MARKER).read_text())
print("bundle:", BUNDLE_DIR)
print("built:", info.get("created_utc"), "| commit:", info.get("git_commit"),
      "| dirty:", info.get("git_dirty"))

if REPO_DIR.exists():
    shutil.rmtree(REPO_DIR)
shutil.copytree(BUNDLE_DIR / "src" / "ARC-AGI-3-Agents", REPO_DIR)
print("copied source to", REPO_DIR)

try:
    import openai
    print("openai available:", openai.__version__)
except ImportError:
    subprocess.check_call(
        [sys.executable, "-m", "pip", "install", "--quiet", "--no-index",
         "--disable-pip-version-check",
         "--find-links", str(BUNDLE_DIR / "wheels"), "openai"]
    )
    import openai
    print("openai installed from bundle wheels:", openai.__version__)
"""

_CELL_VLLM_MD = """\
## 3. Install and launch the vLLM server

The wheelhouse installs into an isolated `--target` directory; only the server
subprocess gets it on `PYTHONPATH`, so the harness environment stays clean.
Flags mirror the harness's registry entry for `qwen3.6-27b` (qwen3_coder tool
parser, qwen3 reasoning parser) at `MAX_MODEL_LEN` context, with `SAMPLING` as
the server-side default generation config. Two smoke tests (text + vision)
must pass before the games start.
"""

_CELL_VLLM = """\
def dataset_dir(owner, slug):
    # Kaggle mounts datasets at /kaggle/input/<slug> or /kaggle/input/datasets/<owner>/<slug>.
    for cand in (Path("/kaggle/input") / slug, Path("/kaggle/input/datasets") / owner / slug):
        if cand.exists():
            return cand
    raise FileNotFoundError(f"Dataset {owner}/{slug} is not attached to this notebook")


WHEELHOUSE = dataset_dir("driessmit1", "arc3-vllm-h100-wheelhouse-v3")
MODEL_DATASET = dataset_dir("driessmit1", "vrfai-qwen3-6-27b-fp8-hf-snapshot")


def resolve_model_path(root):
    if (root / "config.json").exists():
        return root
    for cfg in sorted(root.rglob("config.json")):
        return cfg.parent
    raise FileNotFoundError(f"No config.json under {root}")


MODEL_PATH = resolve_model_path(MODEL_DATASET)
print("wheelhouse:", WHEELHOUSE)
print("model path:", MODEL_PATH)

stamp = VLLM_SITE_PACKAGES / ".install-stamp"
if not stamp.exists():
    shutil.rmtree(VLLM_SITE_PACKAGES, ignore_errors=True)
    VLLM_SITE_PACKAGES.mkdir(parents=True, exist_ok=True)
    print("Installing vLLM wheelhouse into", VLLM_SITE_PACKAGES, flush=True)
    subprocess.check_call(
        [
            sys.executable, "-m", "pip", "install",
            "--no-index", "--find-links", str(WHEELHOUSE),
            "--requirement", str(WHEELHOUSE / "requirements.lock"),
            "--target", str(VLLM_SITE_PACKAGES),
            "--upgrade", "--ignore-installed", "--only-binary", ":all:",
            "--no-compile", "--disable-pip-version-check", "--no-warn-conflicts",
        ]
    )
    stamp.write_text("arc3-vllm-h100-wheelhouse-v3")


def vllm_env():
    env = os.environ.copy()
    existing = env.get("PYTHONPATH", "")
    env["PYTHONPATH"] = str(VLLM_SITE_PACKAGES) + (os.pathsep + existing if existing else "")
    env.update(
        {
            "USE_TF": "0",
            "TRANSFORMERS_NO_TF": "1",
            "TRANSFORMERS_NO_TORCHVISION": "1",
            "VLLM_NO_USAGE_STATS": "1",
            "VLLM_WORKER_MULTIPROC_METHOD": "spawn",
        }
    )
    return env


vllm_cmd = [
    sys.executable, "-m", "vllm.entrypoints.openai.api_server",
    "--model", str(MODEL_PATH),
    "--served-model-name", MODEL_KEY,
    "--host", "127.0.0.1",
    "--port", str(VLLM_PORT),
    "--enable-auto-tool-choice",
    "--tool-call-parser", "qwen3_coder",
    "--reasoning-parser", "qwen3",
    "--max-model-len", str(MAX_MODEL_LEN),
    "--gpu-memory-utilization", str(GPU_MEMORY_UTILIZATION),
    "--enable-prefix-caching",
    "--generation-config", "vllm",
    "--override-generation-config", json.dumps(SAMPLING),
    "--default-chat-template-kwargs", '{"preserve_thinking": true}',
]
if ENABLE_MTP:
    vllm_cmd += ["--speculative-config",
                 '{"method": "qwen3_next_mtp", "num_speculative_tokens": 2}']

print("Starting vLLM:", " ".join(vllm_cmd), flush=True)
vllm_log_handle = VLLM_LOG.open("w")
vllm_proc = subprocess.Popen(vllm_cmd, env=vllm_env(),
                             stdout=vllm_log_handle, stderr=subprocess.STDOUT)
VLLM_BASE_URL = f"http://127.0.0.1:{VLLM_PORT}/v1"


def request_json(url, payload=None, timeout=120):
    data = None if payload is None else json.dumps(payload).encode()
    req = urllib.request.Request(url, data=data, headers={"Content-Type": "application/json"})
    with urllib.request.urlopen(req, timeout=timeout) as response:
        return json.loads(response.read().decode())


def _vllm_log_tail(lines=60):
    if not VLLM_LOG.exists():
        return ""
    return "\\n".join(VLLM_LOG.read_text(errors="replace").splitlines()[-lines:])


def wait_for_vllm(timeout_s=1800):
    deadline = time.monotonic() + timeout_s
    while time.monotonic() < deadline:
        if vllm_proc.poll() is not None:
            raise RuntimeError(
                f"vLLM exited early (code {vllm_proc.returncode}):\\n{_vllm_log_tail()}"
            )
        try:
            request_json(VLLM_BASE_URL + "/models", timeout=5)
            print("vLLM server ready", flush=True)
            return
        except Exception:
            time.sleep(5)
    raise TimeoutError(f"vLLM not ready after {timeout_s}s:\\n{_vllm_log_tail()}")


wait_for_vllm()

# --- Smoke test 1: plain text ------------------------------------------------
resp = request_json(
    VLLM_BASE_URL + "/chat/completions",
    {
        "model": MODEL_KEY,
        "temperature": 0.0,
        "max_tokens": 96,
        "chat_template_kwargs": {"enable_thinking": False},
        "messages": [{"role": "user", "content": "Answer in one short sentence: what is 2 + 2?"}],
    },
    timeout=300,
)
msg = resp["choices"][0]["message"]
print("TEXT SMOKE:", (msg.get("content") or msg.get("reasoning_content") or "").strip())

# --- Smoke test 2: vision (the harness sends grid images) --------------------
import base64
import io

from PIL import Image

buf = io.BytesIO()
Image.new("RGB", (64, 64), (255, 0, 0)).save(buf, format="PNG")
image_url = "data:image/png;base64," + base64.b64encode(buf.getvalue()).decode()
resp = request_json(
    VLLM_BASE_URL + "/chat/completions",
    {
        "model": MODEL_KEY,
        "temperature": 0.0,
        "max_tokens": 96,
        "chat_template_kwargs": {"enable_thinking": False},
        "messages": [{
            "role": "user",
            "content": [
                {"type": "text", "text": "Answer in one short sentence: what color is this square?"},
                {"type": "image_url", "image_url": {"url": image_url}},
            ],
        }],
    },
    timeout=300,
)
msg = resp["choices"][0]["message"]
print("VISION SMOKE:", (msg.get("content") or msg.get("reasoning_content") or "").strip())
"""

_CELL_HARNESS_MD = """\
## 4. Configure the harness

Everything is driven by environment variables: the vLLM backend attaches to
the already-running server (`VLLM_AUTO_START=0`), the Swarm caps concurrent
games, and the diagnostic-only `trace.jsonl` (full VLM I/O) is suppressed to
protect the 20 GB working-directory quota.
"""

_CELL_HARNESS = """\
os.environ.update(
    {
        "CONTINUAL_HARNESS_VLM_BACKEND": "vllm",
        "VLLM_MODEL": MODEL_KEY,
        "VLLM_BASE_URL": VLLM_BASE_URL,
        "VLLM_AUTO_START": "0",
        "VLLM_MAX_MODEL_LEN": str(MAX_MODEL_LEN),
        "SWARM_MAX_CONCURRENT_GAMES": str(MAX_CONCURRENT_GAMES),
        "CONTINUAL_HARNESS_DISABLE_TRACE": "1",
        "RECORDINGS_DIR": str(WORKING_DIR / "arc_recordings"),
        "ARC_API_KEY": os.environ.get("ARC_API_KEY", "test-key-123"),
    }
)
print("harness configured for", MODEL_KEY, "at", VLLM_BASE_URL)
"""

_CELL_RUN_MD = """\
## 5. Play the games

Rerun: wait for the Kaggle gateway, then play the live competition Arcade
(`OPERATION_MODE=competition`). Interactive: play the competition's bundled
environment files offline. Either way `main.py` runs as a subprocess; at the
soft deadline it gets SIGINT so its handler closes the scorecard cleanly.
The vLLM server is torn down afterwards even if the run raises.
"""

_CELL_RUN = """\
def wait_for_gateway(base_url, timeout_s=900):
    deadline = time.monotonic() + timeout_s
    last_error = ""
    while time.monotonic() < deadline:
        try:
            with urllib.request.urlopen(base_url + "/api/games", timeout=10) as response:
                if response.status < 500:
                    return
        except urllib.error.HTTPError as exc:
            if exc.code < 500:
                return
            last_error = repr(exc)
        except Exception as exc:
            last_error = repr(exc)
        time.sleep(5)
    raise RuntimeError(f"Kaggle gateway did not become ready: {last_error}")


run_env = os.environ.copy()
if TRUE_SUBMISSION:
    run_env.update(
        {
            "OPERATION_MODE": "competition",
            "ARC_BASE_URL": "http://gateway:8001",
            "SCHEME": "http",
            "HOST": "gateway",
            "PORT": "8001",
        }
    )
    budget_s = RERUN_BUDGET_S
    print("Waiting for the evaluation gateway ...", flush=True)
    wait_for_gateway("http://gateway:8001")
else:
    run_env.update(
        {
            "OPERATION_MODE": "offline",
            "ENVIRONMENTS_DIR": str(ENV_FILES_DIR),
        }
    )
    budget_s = TEST_BUDGET_S

deadline = NOTEBOOK_START + budget_s
print(f"Game budget: {deadline - time.monotonic():.0f}s remaining", flush=True)

proc = subprocess.Popen(
    [sys.executable, "main.py", "--agent=continualharness"],
    cwd=str(REPO_DIR),
    env=run_env,
    stdout=subprocess.PIPE,
    stderr=subprocess.STDOUT,
    text=True,
)


def _pump(pipe):
    for line in iter(pipe.readline, ""):
        print(line, end="", flush=True)


threading.Thread(target=_pump, args=(proc.stdout,), daemon=True).start()

try:
    while proc.poll() is None:
        if time.monotonic() > deadline:
            print("\\n*** Soft deadline reached; sending SIGINT for a clean shutdown", flush=True)
            proc.send_signal(signal.SIGINT)
            try:
                proc.wait(timeout=180)
            except subprocess.TimeoutExpired:
                proc.terminate()
                try:
                    proc.wait(timeout=30)
                except subprocess.TimeoutExpired:
                    proc.kill()
            break
        time.sleep(10)
    proc.wait()
    print("\\nmain.py exit code:", proc.returncode, flush=True)

    if not TRUE_SUBMISSION:
        # An offline run isn't scored, but Kaggle still expects a submission file.
        import pandas as pd

        pd.DataFrame(
            [["1_0", "1", True, 1]],
            columns=["row_id", "game_id", "end_of_game", "score"],
        ).to_parquet(WORKING_DIR / "submission.parquet", index=False)
        print("Wrote placeholder submission.parquet")
finally:
    print("Stopping vLLM server", flush=True)
    vllm_proc.terminate()
    try:
        vllm_proc.wait(timeout=60)
    except subprocess.TimeoutExpired:
        vllm_proc.kill()
    vllm_log_handle.close()
    # ~20 GB of wheels/libs would blow the working-directory quota when Kaggle
    # packages the notebook output.
    shutil.rmtree(VLLM_SITE_PACKAGES, ignore_errors=True)
    print("Removed", VLLM_SITE_PACKAGES, flush=True)
"""

_CELL_RESULTS_MD = """\
## 6. Results

Per-run scorecard and log tail. Full artifacts (per-game memory/skills/
subagents/prompt snapshots, trajectories, recordings) live under
`ARC-AGI-3-Agents/logs/` in the notebook output.
"""

_CELL_RESULTS = """\
logs_root = REPO_DIR / "logs"
for run_dir in sorted(p for p in logs_root.glob("*") if p.is_dir()):
    print("=" * 88)
    print("Run:", run_dir.name)
    manifest_path = run_dir / "manifest.json"
    if manifest_path.exists():
        manifest = json.loads(manifest_path.read_text())
        print("status:", manifest.get("status"), "| games:", manifest.get("games"))
    scorecard_path = run_dir / "scorecard.final.json"
    if scorecard_path.exists():
        scorecard = json.loads(scorecard_path.read_text())
        cards = scorecard.get("cards") or {}
        if isinstance(cards, dict):
            for game_id, card in sorted(cards.items()):
                if isinstance(card, dict):
                    summary = {k: card.get(k) for k in ("score", "total_plays", "total_actions") if k in card}
                    print(f"  {game_id}: {summary}")
        else:
            print(json.dumps(scorecard, indent=2)[:2000])
    log_path = run_dir / "run.log"
    if log_path.exists():
        print("--- run.log tail ---")
        print("\\n".join(log_path.read_text(errors="replace").splitlines()[-30:]))
"""

NOTEBOOK_CELLS: tuple[tuple[str, str], ...] = (
    ("markdown", _CELL_INTRO_MD),
    ("code", _CELL_SETUP),
    ("markdown", _CELL_ARC_MD),
    ("code", _CELL_ARC),
    ("markdown", _CELL_BUNDLE_MD),
    ("code", _CELL_BUNDLE),
    ("markdown", _CELL_VLLM_MD),
    ("code", _CELL_VLLM),
    ("markdown", _CELL_HARNESS_MD),
    ("code", _CELL_HARNESS),
    ("markdown", _CELL_RUN_MD),
    ("code", _CELL_RUN),
    ("markdown", _CELL_RESULTS_MD),
    ("code", _CELL_RESULTS),
)


def build_notebook() -> str:
    cells: list[dict[str, object]] = []
    for index, (cell_type, source) in enumerate(NOTEBOOK_CELLS):
        cell: dict[str, object] = {
            "id": f"cell-{index}",
            "cell_type": cell_type,
            "metadata": {},
            "source": source.rstrip("\n"),
        }
        if cell_type == "code":
            cell["execution_count"] = None
            cell["outputs"] = []
        cells.append(cell)
    notebook = {
        "nbformat": 4,
        "nbformat_minor": 5,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3",
            },
            "language_info": {"name": "python", "version": "3.12"},
        },
        "cells": cells,
    }
    return json.dumps(notebook, indent=1) + "\n"


def validate_notebook_code() -> None:
    """Every code cell must at least be valid Python."""
    for index, (cell_type, source) in enumerate(NOTEBOOK_CELLS):
        if cell_type == "code":
            ast.parse(source, filename=f"<notebook cell {index}>")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--skip-wheels",
        action="store_true",
        help="Reuse (or omit) kaggle/dist/wheels instead of running pip download.",
    )
    parser.add_argument(
        "--dist-dir",
        type=Path,
        default=DEFAULT_DIST_DIR,
        help=f"Output directory (default: {DEFAULT_DIST_DIR}).",
    )
    args = parser.parse_args(argv)

    dist_dir: Path = args.dist_dir
    wheels_dir = dist_dir / "wheels"

    sources = collect_sources()
    check_imports(sources)
    print(f"Bundling {len(sources) + 1} source files (import check passed)")

    if not args.skip_wheels:
        download_wheels(wheels_dir)
    elif not wheels_dir.is_dir():
        print("--skip-wheels: no wheels directory; bundle will carry no wheels")

    write_zip(dist_dir / BUNDLE_ZIP_NAME, sources, wheels_dir)

    validate_notebook_code()
    notebook_path = dist_dir / NOTEBOOK_NAME
    notebook_path.write_text(build_notebook(), encoding="utf-8")
    print(f"Wrote {notebook_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
